version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "password1*"
    ports:
      - "1433:1433"
    restart: unless-stopped

  vaulty:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=VAULTY_DB;User Id=vaulty_user;Password=password1*;"
    ports:
      - "5000:80" # Adjust depending on your app
    restart: unless-stopped
